# Generated by Django 4.2.23 on 2025-08-24 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_username_alter_profile_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='seen',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
