# Generated by Django 4.2.23 on 2025-08-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_chatmessage_seen_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
