# Generated by Django 4.2.23 on 2025-08-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
